### ISSUE TITLE
Error unknown send request

### ISSUE THREAD

**Issue by Furiousness** [Divdude77/Instagram-Page-Automator#7]
I ran it once last night and it worked fine but now it comes up with this error wherre its not sending.

\Downloads\Instagram-Page-Automator-main\Instagram-Page-Automator-main\memepage.py", line 74, in <module>
    submitted_memes.append(i[0])
IndexError: list index out of range
2022-08-28 12:07:11,551 - INFO - Total requests: 31

Any ideas?

**Comment by Divdude77** [comment]
Hey!
Could you send me the contents of posted.csv?

**Comment by Divdude77** [comment]
Please do respond or i'll have to close this issue

**Comment by Furiousness** [comment]
Hey sorry I didn’t see this until now but I. Will send them tomorrow when I have access to my computer

**Comment by Divdude77** [comment]
Alright

**Comment by Furiousness** [comment]
sample,2022-01-01
wzhfq0,2022-08-28

Those are the only contents

**Comment by Divdude77** [comment]
could you check if theres a blank line in the file?

**Comment by Divdude77** [comment]
Try changing lines 73 to 75 (both included) with this block of code:
```python
for i in csv.reader(f):
    if i:
        submitted_memes.append(i[0])
f.close()
```

**Comment by Furiousness** [comment]
Yep I’ll try those today

**Comment by Furiousness** [comment]
![Capture](https://user-images.githubusercontent.com/34078369/187830250-932665e1-b7f7-47b9-a625-608fd761c6b1.PNG)

Thats what the code looks like now and the error now says this

   if i:
    ^
IndentationError: expected an indented block after 'for' statement on line 73

I tried to change the indentation but I wasn't sure wehre or how?

**Comment by Divdude77** [comment]
Ah, make sure it's looking like this:
<img width="348" alt="Screen Shot 2022-09-01 at 8 45 03 AM" src="https://user-images.githubusercontent.com/75612147/187833231-8edc2023-b8e9-4ac1-a0ca-a8e25fe68aca.png">
Make sure f.close() at the same indent as the line f = open(...) and if i statement is moved one indent inside and the submitted_memes.append() statement is also moved an indent inside.

**Comment by Furiousness** [comment]
Ok so that worked and now its saying its logged in and says

    })
    }
  })
}());
</script>
    </body>
</html>

2022-09-01 08:42:50,322 - ERROR - Error unknown send request

Then it loads more and after a couple of seconds says

    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response
2022-09-01 08:42:57,390 - INFO - Total requests: 31

Before that line is a bunch of lines where its just saying where the files are (ex. C:\Users\Downloads" line 33, in refresh)

And nothing gets posted

**Comment by Divdude77** [comment]
That seems to be an error in the reddit api. 
I can't replicate it, maybe try again after a while?
I'll look further into it, and update you accordingly.

**Comment by Furiousness** [comment]
Ok thanks maybe I’ll try making another api and do that

**Comment by Divdude77** [comment]
Hold on, try this. Change the whole line to this:
reddit = praw.Reddit(
    client_id="client id",
    client_secret="client secret",
    redirect_uri="http://localhost:8080",
    user_agent="memeboi",
)

**Comment by Furiousness** [comment]
Which line?

**Comment by Divdude77** [comment]
The creating a reddit instance line (line 45)

**Comment by Furiousness** [comment]
sorry, do you have any update?

**Comment by Divdude77** [comment]
Hey! So I'm not sure why this error is caused, probably you're on cooldown by the Instagram API. Try again after maybe 2 days? I'm not really sure.

**Comment by Furiousness** [comment]
Ok I will thanks

**Comment by Divdude77** [comment]
Did you manage to get it to work? I need to close this issue.

**Comment by Divdude77** [comment]
Closed due to no response
